add_item:
  name: Add Item
  description: Add an item to a Koplista shopping list
  fields:
    list_id:
      name: List ID
      description: ID of the shopping list (defaults to "default" if not specified)
      required: false
      example: "default"
      selector:
        text:
    item:
      name: Item
      description: Name of the item to add
      required: true
      example: "Mj√∂lk"
      selector:
        text:
